### ISSUE TITLE
source language NL not recognized

### ISSUE THREAD

**Issue by dmzoneill** [plainheart/bing-translate-api#13]
It translates from English to other languages fine.
But it doesn't seem to want to translate from Dutch to English?

It seems to ignore that i'm using dutch and chooses German instead, either way i don't get English.

I'm using https://www.npmjs.com/package/bing-translate-api

code
```
      console.log(msg);
      console.log(source_lang);
      console.log(target_lang);

      translate(msg, source_lang, target_lang, true, true).then(res => {
        console.log(res);
      }).catch(err => {
        console.error(err);
      });
```

result
```
was sold ichor sagen
nl
en

{
  text: 'was sold ichor sagen',
  userLang: 'nl',
  translation: 'was sold ichor sagen',
  language: { from: 'de', to: 'en', score: 1 },
  correctedText: 'was soll ich sagen',
  raw: [ { translations: [Array], detectedLanguage: [Object] } ]
}

```

**Comment by dmzoneill** [comment]
works fine from PT -> EN

something going on with NL

**Comment by plainheart** [comment]
I'm not sure but it seems `'was sold ichor sagen'` is not `nl` but `de`?
