### ISSUE TITLE
HTTPError: Response code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by Oscaner** [plainheart/bing-translate-api#14]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/26829325/209301483-8f4ce771-39b3-4fd5-8ad8-d59e7b05f509.png">

**Comment by plainheart** [comment]
As the error information shows, you might request too many times in a time period. Just try it again later.

**Comment by Oscaner** [comment]
Hi @plainheart ,

I created a PR to bypass "Too Many Requests" error, pls take a look.

**Comment by wanghao950827** [comment]
I created a PR to bypass "Too Many Requests" error, pls take a look.
How it was achieved?

> 你好@plainheart,
> 
> 我创建了一个 PR 来绕过“太多请求”错误，请看一下。
> 
> 更改对我来说很好，现在我不会提示“太多请求”错误。



> 你好@plainheart,
> 
> 我创建了一个 PR 来绕过“太多请求”错误，请看一下。
> 
> 更改对我来说很好，现在我不会提示“太多请求”错误。

How do the problem get solved?

**Comment by psamant55** [comment]
I have tried to host it with render.com.

It is giving me the same response. 

Can you add an example of using proxy agents.

**Comment by troyeguo** [comment]
Get the same error at the first try. I don't think I was sending too many requests.

**Comment by RwGrid** [comment]
yes please , give us example with proxy agents

**Comment by plainheart** [comment]
Hi, all. I'm going to release v3.0.0, in which a new EPT mode with a lower (or no?) rate limit was added. Before publishing, I would appreciate your test and feedback. Just try the latest code of the main branch of this repository.
