### ISSUE TITLE
Something went wrong! The response is {"statusCode":205,"errorMessage":""}

### ISSUE THREAD

**Issue by thesammet** [plainheart/bing-translate-api#19]
const { translate } = require('bing-translate-api');
const translationFunction = async (vocabulary, mainLanguage, languageTo) => {
    try {
        const res = await translate(vocabulary.toLowerCase(), mainLanguage, languageTo, true)
        return res
    } catch (error) {
        return error
    }
}
module.exports = translationFunction 

This is my node.js code piece. All values are correct and the system was worked before nearly 1 months ago. But nowadays that error shown.
The response is Something went wrong! The response is {"statusCode":205,"errorMessage":""}.  The status 205 is reset content but I can't find any relation with the code.
Please can you fix that

**Comment by plainheart** [comment]
Refer to #16. Please upgrade to v2.7.0 or later and try again.

**Comment by thesammet** [comment]
Thanks so much.
