### ISSUE TITLE
crash: redirects is empty

### ISSUE THREAD

**Issue by rerender2021** [plainheart/bing-translate-api#21]
# Description

The API may have changed, `redirects` returned is empty, so it throws.

![image](https://user-images.githubusercontent.com/87927336/218895306-55843fd4-7725-46c1-9de0-a23bb62aee89.png)

![image](https://user-images.githubusercontent.com/87927336/218895525-06ef8a55-7dd8-4457-ae52-f4f69b407cc9.png)

# Workaround

hardcode subdomain as "www" or use requestUrl as `redirects[0]` fallback

![image](https://user-images.githubusercontent.com/87927336/218898424-b4bdf1a0-14f9-4bb7-9c86-8406946f15ab.png)

**Comment by plainheart** [comment]
What version of `got` are you using? I tried but couldn't reproduce this error. This library requires got v11, instead of v12.

**Comment by plainheart** [comment]
Thanks for your feedback. It seems a potential bug that I didn't notice.

**Comment by plainheart** [comment]
Fixed in [v2.9.0](https://github.com/plainheart/bing-translate-api/releases/tag/v2.9.0) :)
