### ISSUE TITLE
Response code 404 (Not Found)

### ISSUE THREAD

**Issue by Daniel-Griffiths** [plainheart/bing-translate-api#22]
This library worked correctly yesterday, but stopped working earlier today. The `translate` function returns a `Response code 404 (Not Found)` error. 

Perhaps the translate endpoint has changed url?

**Comment by plainheart** [comment]
Hi, can you provide more information? The [auto test](https://github.com/plainheart/bing-translate-api/actions/runs/4805469467/jobs/8551914457) shows that it still works well.

**Comment by Daniel-Griffiths** [comment]
Hey @plainheart I tested this morning and it seems to be working again now so I will close this issue.

Maybe the API was having some issues.
