### ISSUE TITLE
"name":"HTTPError","code":"ERR_NON_2XX_3XX_RESPONSE"

### ISSUE THREAD

**Issue by 1103442828** [plainheart/bing-translate-api#27]
近期出现以下问题，我看到一个相似的issues，但我这边没有短期多次请求

> {"name":"HTTPError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1699604582921,"socket":1699604582925,"lookup":1699604582979,"connect":1699604583017,"secureConnect":1699604583059,"upload":1699604583059,"response":1699604603159,"end":1699604603163,"phases":{"wait":4,"dns":54,"tcp":38,"tls":42,"request":0,"firstByte":20100,"download":4,"total":20242}}}

**Comment by plainheart** [comment]
还有更详细的信息吗，比如 bing 的原始返回结果，类似 `{ code: 0, message: "XXX"` 这样。

**Comment by plainheart** [comment]
貌似国内 bing translator 的服务出问题了，我这边打开网站接口也不通了。

<img src="https://github.com/plainheart/bing-translate-api/assets/26999792/3f60dbe5-1271-41ab-a5b4-c0725eb78d5c" width="400">

**Comment by Carrotzpc** [comment]
同样的问题 +1
