### ISSUE TITLE
feature request!

### ISSUE THREAD

**Issue by AliAryanTech** [plainheart/bing-translate-api#28]
Bing Translator apiKey support?

**Comment by plainheart** [comment]
This library differs from the official paid service, it uses the free website service endpoint, so it doesn't need and support an API key.

**Comment by AliAryanTech** [comment]
> Are there additional modules with official API support? I couldn't find any; your assistance would be appreciated. Sometimes it says "Too many request"

**Comment by plainheart** [comment]
I don't know if there are some official modules for Node.js, but I think I would try to add the support later if it's possible.

**Comment by AliAryanTech** [comment]
Okay, thanks

**Comment by plainheart** [comment]
Hi @AliAryanTech, I plan to release v3.0.0 soon, in which a new EPT mode with a lower (or no?) rate limit was added. Before publishing, I would appreciate your test and feedback. Just try the latest code of the main branch of this repository.

**Comment by plainheart** [comment]
Hi @AliAryanTech, just let you know the new _**MET**_ mode will be released in v4.0.0 soon. As you mentioned, It supports the official paid service endpoint with your private keys. Besides, it provides a free service that is more stable than the legacy website mode and supports more languages than the _**EPT**_ mode of v3.0.0.

**Comment by AliAryanTech** [comment]
> Hi @AliAryanTech, just let you know the new _**MET**_ mode will be released in v4.0.0 soon. As you mentioned, It supports the official paid service endpoint with your private keys. Besides, it provides a free service that is more stable than the legacy website mode and supports more languages than the _**EPT**_ mode of v3.0.0. See also #34.

Ohh Thank you! My apologies for the delay; college kept me busy. I'll check my notifications as soon as possible.
