### ISSUE TITLE
Implemented this library using java language

### ISSUE THREAD

**Issue by marmot-z** [plainheart/bing-translate-api#29]
Hi, plainheart. Thank you very much for developing such a useful toolkit. Recently I wanted to use bing translate to implement some translation functions, but unfortunately there is no similar toolkit in the java ecosystem, so I imitated this project. A [java version of the tool](https://github.com/marmot-z/bing-translate-api) was created. If you want, can you link it to **Related projects** in the README?

**Comment by plainheart** [comment]
Cool. Please open a PR to add your repo to the related project list.

**Comment by marmot-z** [comment]
> Cool. Please open a PR to add your repo to the related project list.

I submitted this PR : https://github.com/plainheart/bing-translate-api/pull/30
