### ISSUE TITLE
Cannot read property 'translations' of undefined

### ISSUE THREAD

**Issue by codingMASTER398** [plainheart/bing-translate-api#3]
This error occurs after doing lots (around 500 in 30 minutes) of translations
`TypeError: Cannot read property 'translations' of undefined
    at translate (/home/runner/Bibletranslation/node_modules/bing-translate-api/src/index.js:117:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`
I used the same code as in the docs to test.

Its not ratelimiting i think, opening up bing.com and writing some quick code to ping their servers with translations works.

**Comment by codingMASTER398** [comment]
Note: i am using repl.it to translate the bible

**Comment by plainheart** [comment]
Thanks. I tried to fix some potential bugs, but it still can't solve the bing translator's issue that requires the captcha. I tested it 500 times within 30 minutes in my local environment, it works. But it can't even work 1 time in the Travis ci. Maybe it blocked the IP.
