### ISSUE TITLE
Request code 429

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [plainheart/bing-translate-api#7]
Is there any way to prevent it, using auto detector for the input language

**Comment by plainheart** [comment]
The [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) indicates commonly a rate limit reached. Please keep your requests not so frequent. It's just a free API without tokens provided by the Bing translator website, so it can't be compared with those chargeable.

**Comment by Xx-Mohit-xX** [comment]
Alr, I'll keep in mind
