### ISSUE TITLE
showing errors in react-native

### ISSUE THREAD

**Issue by usmandilmeer** [plainheart/bing-translate-api#8]
how can i use this in react native

**Comment by plainheart** [comment]
May I know more about the errors? BTW, you have to run it on your web server like _node_, this library can't be used in the browser environment.

**Comment by usmandilmeer** [comment]
To reload the app press "r"
To open developer menu press "d"

 BUNDLE  ./index.js

error: Error: Unable to resolve module url from C:\Users\ThePkGamerz\Desktop\transapi\node_modules\got\dist\source\index.js: url could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  11 | };
  12 | Object.defineProperty(exports, "__esModule", { value: true });
> 13 | const url_1 = require("url");
     |                        ^
  14 | const create_1 = require("./create");
  15 | const defaults = {
  16 |     options: {
    at ModuleResolver.resolveDependency (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\node-haste\DependencyGraph.js:288:43)
    at Object.resolve (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at async addDependency (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
    at async Promise.all (index 1)

**Comment by usmandilmeer** [comment]
> To reload the app press "r" To open developer menu press "d"
> 
> BUNDLE ./index.js
> 
> error: Error: Unable to resolve module url from C:\Users\ThePkGamerz\Desktop\transapi\node_modules\got\dist\source\index.js: url could not be found within the project or in these directories: node_modules
> 
> If you are sure the module exists, try these steps:
> 
> 1. Clear watchman watches: watchman watch-del-all
> 2. Delete node_modules and run yarn install
> 3. Reset Metro's cache: yarn start --reset-cache
> 4. Remove the cache: rm -rf /tmp/metro-*
>    11 | };
>    12 | Object.defineProperty(exports, "__esModule", { value: true });
> 
> > 13 | const url_1 = require("url");
> > |                        ^
> > 14 | const create_1 = require("./create");
> > 15 | const defaults = {
> > 16 |     options: {
> > at ModuleResolver.resolveDependency (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:129:15)
> > at DependencyGraph.resolveDependency (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\node-haste\DependencyGraph.js:288:43)
> > at Object.resolve (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\lib\transformHelpers.js:129:24)
> > at resolve (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
> > at C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
> > at Array.reduce ()
> > at resolveDependencies (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
> > at processModule (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
> > at async addDependency (C:\Users\ThePkGamerz\Desktop\transapi\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
> > at async Promise.all (index 1)

showing this error in my react native android project
can you please solve these issues?
