### ISSUE TITLE
Not supported Georgian

### ISSUE THREAD

**Issue by Tveyni** [plainheart/bing-translate-api#9]
Hello, why is there no Georgian language?

**Comment by plainheart** [comment]
Hi, sorry for missing the Georgian language. The supported language list was generated about 1 year ago, it may be missing this language at that time. I'll regenerate a new list soon and release a new version. Thanks!

**Comment by plainheart** [comment]
Released [v2.3.0](https://www.npmjs.com/package/bing-translate-api/v/2.3.0) on npm.
